// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvxubelswoxcfunljgvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2eHViZWxzd294Y2Z1bmxqZ3ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxMzMyNTMsImV4cCI6MjA1MzcwOTI1M30.XmyPE4BTDyvAZlVvYLYlOs2iZIHPrOwQdbX46jh3gV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);